Repository canonical/cookie-policy, pull requests merged in 2019-02, with the labels that each got.

#21 Remove built assets, use prepublishOnly instead
  .gitignore
  .prettierignore
  build/css/cookie-policy.css
  build/js/cookie-policy.js
  package.json
Labels: Review: Code needed, Review: QA needed

#23 Use "prepublish" instead of "prepublishOnly"
  package.json
Labels: Review: Code +1, Review: QA +1

#25 Improve Vanilla include
  src/js/cookie-policy.js
  src/sass/_base-typography.scss
  src/sass/_patterns-notification.scss
  src/sass/cookie-policy.scss
Labels: Review: QA +1

#26 Bump version to 1.1.0
  package.json
Labels: Review: Code +1
