Repository canonical/cookie-policy, pull requests merged in 2020-10, with the labels that each got.

#83 Add pageview if the user excepts cookies
  package.json
  src/js/utils.js
Labels: Review: Code +1, Review: QA +1

#84 Add SameSite:Lax to cookie policy
  src/js/utils.js
Labels: Review: Code +1, Review: QA +1, hacktoberfest-accepted

#88 Expire the cookie after a year instead of a day
  src/js/utils.js
Labels: Review: Code +1, Review: QA +1, hacktoberfest-accepted

#85 Improve the revoke example in the README
  README.md
Labels: Review: Code +1, hacktoberfest-accepted

#86 Bump the version to 3.0.4
  package.json
Labels: Review: Code +1, hacktoberfest-accepted

#90 Improve iOS Safari UI
  src/sass/_patterns-modal.scss
  src/sass/cookie-policy.scss
Labels: Review: Code +1, Review: QA +1
