Repository canonical/cookie-policy, pull requests merged in 2024-06, with the labels that each got.

#178 fix: Ensure 'essential' cookies are always checked and disable the toggle
  src/js/content.js
  src/js/control.js
Labels: Review: QA +1, Review: Code +1

#179 Bump to 3.6.4
  package.json
Labels: Review: Code +1

#176 Update README.md
  README.md
Labels: Review: Code needed
